title: Mi primer sitio con Jekyll.
author: Marjori Flores.
description: >-
  Sitio de ejemplo usando Jekyll.
twitter_username: yo
github_username: yo

baseurl: "/jekyll-sitio" 
url: "https://marjorifc.github.io" 

theme: jekyll-theme-architect
plugins:
  - jekyll-feed



