

title: Mi primer sitio con Jekyll.
author: Marjori Flores.
description: >- # this means to ignore newlines until "baseurl:"
  Sitio de ejemplo usando Jekyll.
twitter_username: yo
github_username:  yo

# Build settings
theme: minima
plugins:
  - jekyll-feed



